### ISSUE TITLE
updateModal needed for transitions

### ISSUE THREAD

**Issue by robhicks** [dwmkerr/angular-modal-service#13]
Take your example:
```javascript
ModalService.showModal({
  templateUrl: "some/template.html",
  controller: "SomeController"
}).then(function(modal) {
  // only called on success...
}).catch(function(error) {
  // error contains a detailed error message.
  console.log(error);
});
```

I would be nice to keep the modal open and update it. So, in the error handler, do something like this:

```javascript
ModalService.showModal({
  templateUrl: "some/template.html",
  controller: "SomeController"
}).then(function(modal) {
  // only called on success...
}).catch(function(error) {
  ModalService.updateModal({
  templateUrl: "error/template.html",
  controller: "errorController"
}).then(function(modal) {
  modal.element.modal()
})
});
```

**Comment by dwmkerr** [comment]
@robhicks @nobodyman the `catch` function should only be hit when something mechanistic fails, which means that in all likelihood we cannot expect the modal to be in a state where we can update it with error information. I would probably aim for handling this in the application like so:

ModalService.showModal({
  templateUrl: "some/template.html",
  controller: "SomeController"
}).then(function(modal) {
  // only called on success...
}).catch(function(error) {
  AlertService.showError("Something went wrong");
});

the `AlertService` would be defined by the app, it could show an alert, a modal, log or whatever. But assuming that we can actually somehow interact with the modal is probably wrong because we know that we have failed to create it. Thoughts?
