### ISSUE TITLE
Closing modal locks the screen with full screen shadow

### ISSUE THREAD

**Issue by mustafabereket** [dwmkerr/angular-modal-service#169]
I am using this modal service. But whenever I try to close the modal, the modal goes away but it leaves a shadow behind which locks the screen and prevents me from doing anything.
Any idea how I can fix this?

**Comment by pdemilly** [comment]
Same issue here. The only way is too add data-dismiss="modal" to my button but then I get a race condition where the close promise seems to be executed automatically and before my own explicit call to close(result) in the handler of the button clck

See fiddle. [](http://jsfiddle.net/pdemilly/my7wwqbu/1/)

**Comment by TristanVeyet** [comment]
I had the same problem today while it was working before (i did not notice it for months).
Using "git bisect" to find the guilty commit, i found that the problem was that i was using `<!doctype html>` on top of my modal html template.
Maybe my solution could be a hint for your problem.

**Comment by rbatllet** [comment]
If you cancel or close the modal you have to add this to the button actions before returning to the main window:

```
$element.modal('hide');
```

**Comment by fabioel** [comment]
For me adding `data-dismiss="modal"` to the according button fixed the issue

**Comment by Jakobovski** [comment]
You can also use jQuery. Just add an `id` tag to the modal and then   $('#modal-idl').modal('hide');

**Comment by dwmkerr** [comment]
@TristanVeyet thanks for the update, in your case the issue was: https://github.com/dwmkerr/angular-modal-service#im-using-a-bootstrap-modal-and-the-backdrop-doesnt-fade-away

For others, check: https://github.com/dwmkerr/angular-modal-service#the-backdrop-still-does-not-fade-away-after-i-call-close-or-i-dont-want-to-use-the-data-dismiss-attribute-on-a-button-how-can-i-close-a-modal-manually

Which should cover these cases!
