### ISSUE TITLE
When I open a modal through button click, then I hit enter it opens another modal

### ISSUE THREAD

**Issue by warjohn123** [dwmkerr/angular-modal-service#201]

**Comment by dwmkerr** [comment]
This might be because you still have the original button element focused with the keyboard. This I believe is a bootstrap issue. I would suggest as a workaround you:

1. Make sure the element you want to have initially focused has an id (such as `#defaultFocus`).
2. On controller startup, use jQuery to find that element and focus is (such `$('#defaultFocus).focus()`)
